CONFIG_ZMK_SLEEP=n

CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# Report peripheral battery to host
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# Disable reporting of dongle battery (always 100%)
CONFIG_BT_BAS=n
CONFIG_ZMK_DISPLAY=y

# Sleep
CONFIG_ZMK_SLEEP=y
# in milliseconds
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=300000
